# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test_units:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: i
      - run: npm test
  # stage:
  e2e_setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ matrix.node-version }}
          restore-keys: |
            ${{ runner.os }}-playwright-
  # stage, test with tag user:
  e2e_user:
    needs: [test_units, e2e_setup]
    runs-on: ubuntu-latest
    steps:
      - name: Run e2e tests with tag 'user'
        run: npx playwright test --grep @user
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-user
          path: playwright-report/
          retention-days: 30
  # stage, test with tag login:
  e2e_login:
    needs: e2e_user
    runs-on: ubuntu-latest
    steps:
      - name: Run e2e tests with tag 'login'
        run: npx playwright test --grep @login
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-login
          path: playwright-report/
          retention-days: 30
  # stage, test with tag register:
  e2e_register:
    needs: e2e_login
    runs-on: ubuntu-latest
    steps:
      - name: Run e2e tests with tag 'register'
        run: npx playwright test --grep @register
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-register
          path: playwright-report/
          retention-days: 30

  # without stage:

  # e2e:
  #   needs: test
  #   timeout-minutes: 60
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Install Playwright Browsers
  #       run: npx playwright install --with-deps
  #     - name: Run Playwright tests
  #       run: npx playwright test
  #     - uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: playwright-report
  #         path: playwright-report/
  #         retention-days: 30
